apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-argo-app-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shiranitz/argo_dev
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
